name: CI/CD Pipeline for Express and Gin APIs

on:
  workflow_dispatch:
    inputs:
      express_image_tag:
        description: 'New Image Tag for Express API'
        required: true
        default: 'latest'
      gin_image_tag:
        description: 'New Image Tag for Gin API'
        required: true
        default: 'latest'

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Amazon ECR
      - name: Log in to ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Build and Push Express API Image
      - name: Build and Push Express API Image
        run: |
          cd express.api
          EXPRESS_TAG=${{ github.event.inputs.express_image_tag }}
          echo "Building Express API image with tag $EXPRESS_TAG"
          docker build -t <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/benchmarks/express-api:$EXPRESS_TAG ./express.api
          docker push <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/benchmarks/express-api:$EXPRESS_TAG

      # Build and Push Gin API Image
      - name: Build and Push Gin API Image
        run: |
          cd gin.api
          GIN_TAG=${{ github.event.inputs.gin_image_tag }}
          echo "Building Gin API image with tag $GIN_TAG"
          docker build -t <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/benchmarks/gin-api:$GIN_TAG ./gin.api
          docker push <aws-account-id>.dkr.ecr.us-east-1.amazonaws.com/benchmarks/gin-api:$GIN_TAG

  deploy-to-eks:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      # Deploy Express API to EKS
      - name: Deploy Express API
        run: |
          cd deploment/express_api
          EXPRESS_TAG=${{ github.event.inputs.express_image_tag }}
          echo "Deploying Express API with tag $EXPRESS_TAG"
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
          kubectl apply -f ingress.yml

      # Deploy Gin API to EKS
      - name: Deploy Gin API
        run: |
          cd deploment/gin_api
          GIN_TAG=${{ github.event.inputs.gin_image_tag }}
          echo "Deploying Gin API with tag $GIN_TAG"
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
          kubectl apply -f ingress.yml